### ISSUE TITLE
 Or a way to convert JASON to YDK I don't want to convert DACK files one by one, I want to convert them all at once.

### ISSUE THREAD

**Issue by Abanoubawny1** [DawnbrandBots/yaml-yugi#154]
Or a way to convert JASON to YDK I don't want to convert DACK files one by one, I want to convert them all at once.

**Comment by kevinlul** [comment]
What are you trying to do? This repository contains information about every Yu-Gi-Oh card but no information on _decks_.

**Comment by kevinlul** [comment]
[JSON](https://en.wikipedia.org/wiki/JSON) isn't a specific format for decks. It's a general format that can be used to store anything, much like say a Word document, so there's really no connection with this project at all and it's not the tool for you. If you want to export decks from Master Duel as YDK, you could try my [Deck transfer for Yu-Gi-Oh! Master Duel](https://github.com/DawnbrandBots/deck-transfer-for-master-duel) extension, but it is one at a time so it seems like that might not work for you. Alternatively, maybe you could see if [YGOPRODECK's companion app](https://ygoprodeck.com/master-duel/companion-app/) does what you want. Whatever the case, unfortunately it's not related to YAML Yugi, so I can't really help you further here.
