### ISSUE TITLE
Add more filed for Master Duel card data

### ISSUE THREAD

**Issue by Unknown51335** [DawnbrandBots/yaml-yugi#159]
Currently, [the JSON data](https://dawnbrandbots.github.io/yaml-yugi/master-duel-raw.json) returned from this link includes the following fields: ["rarity", "attribute", "types", "atk", "lore", ...]. I understand that this data is retrieved from the API, such as [this](https://yugipedia.com/api.php?action=query&format=json&prop=revisions&pageids=712301&rvprop=content).

However, the Yugipedia web page offers additional information that is crucial for a comprehensive Master Duel card database. These include fields like:

Craftable: Whether the card can be crafted in the game.
Release Date (specific to Master Duel): When the card was released in the game.
Included Set (specific to Master Duel): Which set the card is part of in the game.
These fields can be extracted from the HTML content returned by a different API endpoint, such as [this one](https://yugipedia.com/api.php?action=parse&page=1st%20Movement%20Solo%20(Master%20Duel)&format=json&prop=text). Unfortunately, the API response here is in HTML format, which requires additional parsing to extract the necessary fields.

At this time, I haven't found a more straightforward way to retrieve these specific fields from the API. Including these additional fields would significantly enhance the utility of the Master Duel cards database.

**Comment by kevinlul** [comment]
Hi, what you're doing is rendering the wikitext templates, which is roughly equivalent to scraping the HTML pages themselves. The release date and set data actually comes from individual set pages like https://yugipedia.com/wiki/Wings_of_the_Guardian. Work on this is currently tracked in DawnbrandBots/yaml-yugipedia#2 and also previously requested in #76.

**Comment by Unknown51335** [comment]
Thanks for your reply. I understand now. This is a great work.
